### ISSUE TITLE
Tabla de atributos (SHP R_CONSTRUCCION)

### ISSUE THREAD

**Issue by risturiz** [MaptimeBogota/Varios#1]
No sé si esto se pudiese manejar mejor en el wiki... Lo habiamos hablado en una oportunidad anterior, tratar de hacer las equivalencias sobre los "tags" que contiene la capa de Catastro y lo que efectivamente debe incluirse dentro de OSM.

Revisando la capa R_CONSTRUCCION en Qgis tenemos los siguientes campos:

| codigo | terreno_co | tipo_const | tipo_domin | numero_pis | numero_sot | numero_mez | numero_sem | cod_ant |

codigo: 084360003000000010096000000000
terreno_co: 084360003000000010096000000000
tipo_const: CONVENCIONAL
tipo_domin: PRIVADO
numero_pis: 1
numero_sot: 0
numero_mez: 0
numero_sem: 0
cod_ant: 08436000300010096000

La información es tomada del portal IGAC https://geoportal.igac.gov.co/contenido/datos-abiertos-catastro

**Comment by angoca** [comment]
Hola Rafa, pues creé un Wiki en este repositorio para describir eso. De golpe puede ser mejor poner la descripción del proceso en esta página, en vez del Wiki de OSM, ya que el detalle de los datos de Catastro es algo muy particular, y que no tiene relación directa con OSM.

Lo que si podríamos hacer es referenciar este repositorio desde el wiki de OSM.

**Comment by risturiz** [comment]
Excelente... Y efectivamente a eso me refiero, usar Github para todo ( me faltó especificar wiki de Github )... Porque todo lo que se puede ir desarrollando acá digamos que son muchas pruebas de ensayo y error... Colocarlo en el wiki de OSM causaría ruido innecesario
